include: package:lints/recommended.yaml

linter:
  rules:
    unnecessary_brace_in_string_interps: false
    non_constant_identifier_names: false
    avoid_function_literals_in_foreach_calls: false
    prefer_final_fields: false
    prefer_function_declarations_over_variables: false
    hash_and_equals: false
