#!/usr/bin/env bash

check_for_command() {
  which ${1} >/dev/null 2>&1
  if [ ${?} -ne 0 ]
  then
    echo "ERROR: The Command '${1}' is required for the Build Script!"
    exit 1
  fi
}

check_for_command pub
check_for_command dart

if [ ! -d "packages"/ ]; then
  pub install
fi 

dart --checked tool/hop_runner.dart ${@}
